package HW3;

//Generated by Selenium IDE

import HW3.pages.AbstractTest;
import org.json.simple.JSONObject;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.By;

public class FindHighestPriceProductTest extends AbstractTest {
    @Test
    public void FindHighestPrice() throws InterruptedException {
        homePage.openHomePage();
        JSONObject config =(JSONObject) this.base_config.get("FindHighestPriceTest");
        String menuOption = (String) config.get("MenuOptionID");
        shopPage.openShopPage(menuOption);
        shopPage.sortByHighToLow();
        shopPage.getToItembyXpath(0);// first index
      //  String url = shopPage.getItembyXpathOrder();

        productPage.setUrl(driver.getCurrentUrl());
        productPage.setProductName(driver.findElement(By.className("product_title")).getText());
        System.out.println("Highest Price Product: " + productPage.getProductName());

        logger.info("Test {%s} Completed Successfully".formatted(this.getClass().getCanonicalName()));
        js.executeScript("window.scrollTo(0,1500)");
    }

    public static void main(String[] args) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(AddToCartButtonTest.class); // Replace "SampleTest" with the name of your class

        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
