package HW3;

//Generated by Selenium IDE

import HW3.pages.AbstractTest;
import org.json.simple.JSONObject;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.*;
import java.util.List;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class RemoveProductFromCartTest extends AbstractTest {

    @Test
    public void RemoveProduct() throws InterruptedException {
        JSONObject config = readJSON("src/test/java/HW3/jsons/AddToCartJSON.json");

        // Open home page
        homePage.openHomePage();

        // Open store page
        String menuOption = (String) config.get("MenuOptionID");
        homePage.openPage(menuOption);

        // Add first product from the shop to cart
        int XpathIndex = ((Long) config.get("XpathIndex")).intValue();
        String productUrl = shopPage.getToItembyXpath(XpathIndex);

        // View Cart
        productPage.setUrl(productUrl);
        productPage.addProduct();

        // Remove the product from the cart
        productPage.removeProduct();

        logger.info("Test {%s} Completed Successfully".formatted(this.getClass().getCanonicalName()));
        js.executeScript("window.scrollTo(0,1500)");
    }

    private void HandelLogger(String expectedUrl, String checkType) throws InterruptedException {
        if (driver.getCurrentUrl().equals(expectedUrl))
            logger.info(Testing.TestSuccess.toString(checkType) + " Successfully accessed");
        else {
            InterruptedException e = new InterruptedException(" Failed to access");
            logger.info(Testing.TestFail.toString(checkType) + e.getLocalizedMessage());
            throw new InterruptedException();
        }
    }

    public static void main(String[] args) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(RemoveProductFromCartTest.class); // Replace "SampleTest" with the name of your class

        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
