package HW3;

//Generated by Selenium IDE

import HW3.pages.AbstractTest;
import org.json.simple.JSONObject;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

public class SearchProductTest extends AbstractTest {

    @Test
    public void SearchProduct() throws InterruptedException {
        driver.manage().window().setSize(new Dimension(1052, 666));
        JSONObject config =(JSONObject)this.base_config.get("SearchTest");
        homePage.openHomePage();

        String menuOption = (String) config.get("MenuOptionID");
        homePage.openPage(menuOption);

        String searchValue = (String) config.get("searchValue");
        shopPage.searchProductByName(searchValue);

        logger.info("Test {%s} Completed Successfully".formatted(this.getClass().getCanonicalName()));
        js.executeScript("window.scrollTo(0,1500)");
    }


    public static void main(String[] args) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(SearchProductTest.class); // Replace "SampleTest" with the name of your class

        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
