package HW3;

//Generated by Selenium IDE

import HW3.pages.AbstractTest;
import org.json.simple.JSONObject;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

public class SearchForShoesProductTest extends AbstractTest {

    @Test
    public void SearchProduct() throws InterruptedException {
        driver.manage().window().setSize(new Dimension(1052, 666));
        driver.get("https://atid.store/");
        HandelLogger("https://atid.store/", "Website");
        JSONObject config =readJSON("src/test/java/HW3/jsons/searchJSON.json");
        String menuOption = (String) config.get("MenuOptionID");
        driver.findElement(By.id(menuOption)).click();
        HandelLogger("https://atid.store/store/", "Shop");
        String searchValue = (String) config.get("searchValue");
        WebElement textField = driver.findElement(By.cssSelector("#wc-block-search__input-1"));
        textField.sendKeys(searchValue);

        WebElement submit = driver.findElement(By.cssSelector("#block-7 > div > form > div > button"));
        submit.click();
        HandelLogger("https://atid.store/?s="+searchValue+"&post_type=product", "Product("+searchValue+")");

        logger.info("Test {%s} Completed Successfully".formatted(this.getClass().getCanonicalName()));
        js.executeScript("window.scrollTo(0,1500)");
    }

    private void HandelLogger(String expectedUrl, String checkType) throws InterruptedException {
        if (driver.getCurrentUrl().equals(expectedUrl))
            logger.info(Testing.TestSuccess.toString(checkType) + " Successfully accessed");
        else {
            InterruptedException e = new InterruptedException("Failed to access");
            logger.info(Testing.TestFail.toString(checkType) + e.getLocalizedMessage());
            throw new InterruptedException();
        }
    }

    public static void main(String[] args) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(SearchForShoesProductTest.class); // Replace "SampleTest" with the name of your class

        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
