package HW3;

//Generated by Selenium IDE

import HW3.pages.AbstractTest;
import HW3.pages.HomePage;
import HW3.pages.ProductPage;
import HW3.pages.ShopPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import org.apache.logging.log4j.*;

public class SearchForShoesProductTest extends AbstractTest {

    @Test
    public void SearchProduct() throws InterruptedException {
        driver.manage().window().setSize(new Dimension(1052, 666));
        driver.get("https://atid.store/");
        HandelLogger("https://atid.store/", "Website");

        WebElement shop = driver.findElement(By.cssSelector("#menu-item-45 > a"));
        shop.click();
        HandelLogger("https://atid.store/store/", "Shop");

        WebElement textField = driver.findElement(By.cssSelector("#wc-block-search__input-1"));
        textField.sendKeys("Shoe");

        WebElement submit = driver.findElement(By.cssSelector("#block-7 > div > form > div > button"));
        submit.click();
        HandelLogger("https://atid.store/?s=Shoe&post_type=product", "Product(Shoe)");

        logger.info("Test {%s} Completed Successfully".formatted(this.getClass().getCanonicalName()));
        js.executeScript("window.scrollTo(0,1500)");
    }

    private void HandelLogger(String expectedUrl, String checkType) throws InterruptedException {
        if (driver.getCurrentUrl().equals(expectedUrl))
            logger.info(Testing.TestSuccess.toString(checkType) + " Successfully accessed");
        else {
            InterruptedException e = new InterruptedException("Failed to access");
            logger.info(Testing.TestFail.toString(checkType) + e.getLocalizedMessage());
            throw new InterruptedException();
        }
    }

    public static void main(String[] args) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        org.junit.runner.Result result = junit.run(SearchForShoesProductTest.class); // Replace "SampleTest" with the name of your class

        if (result.getFailureCount() > 0) {
            System.out.println("Test failed.");
            System.exit(1);
        } else {
            System.out.println("Test finished successfully.");
            System.exit(0);
        }
    }
}
